# Style setting
# set -g status-style bg=default,fg=white
# set -g pane-border-style fg='#888888'
# set -g pane-active-border-style fg='#888888'
# set -g status-position bottom

# Key binding
## Prefix binding
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

## Pane splitting binding
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Reload tmux config
unbind r
bind r source-file ~/.tmux.conf

# Vim binding
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# Resize and maxi-minimize pane
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
bind M-c attach-session -c "#{pane_current_path}"
set -g mouse on

# remove delay for exiting insert mode with esc in nvim
set -sg escape-time 10

# Enter copy mode for terminal
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
unbind -T copy-mode-vi MouseDragEnd1Pane

# Plugins installation
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'nvim vim'

# set theme
set -g @powerkit_theme "github"
set -g @powerkit_theme_variant "dark"
set -g @powerkit_transparent "true"

run '~/.tmux/plugins/tpm/tpm'
